### ISSUE TITLE
Add the layer_id to the layer description

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-landing-page#304]
The Tile Layers and Vector Layers in the landing page are only referred to by their human readable names. We should also find a way to include their respective `layer_ids` (ex. `road_map`, `world_countries`) in the page. This will help users who are creating maps in Kibana Vega visualizations where the layer_ids need to be known.

**Comment by nreese** [comment]
Thanks. This will be a great addition. I have always found it confusing that there is not tile layer details like the details listed for files. 

It would be great if the default EMS page redirected to a tile layer instead of world countries.

**Comment by nreese** [comment]
https://github.com/elastic/kibana/pull/88440 allows users to specify the EMS baselayer id in `mapStyle` parameter. The EMS layer ids are hard coded in the docs at docs/user/dashboard/vega-reference.asciidoc. These docs need to updated to link to EMS once EMS provides a way to view the ids of the available base layers.
