### ISSUE TITLE
Fail more gracefully if WebGL is not available

### ISSUE THREAD

**Issue by timroes** [elastic/ems-landing-page#33]
If your browser doesn't support WebGL, i.e. because you toggled something around GPU performance (or it's an older browser), we don't fail very gracefully. We will just show an empty page, and throw several errors on the console:

![screenshot-20180712-093829](https://user-images.githubusercontent.com/877229/42619461-61c77b74-85b8-11e8-8393-f8a081a68c40.png)

I think it would be nicer if we would at least show a simple message, that this page requires WebGL.

**Comment by timroes** [comment]
This is also nothing very hard to disable, since you even don't need a flag for it, but you usually can just disable it in the settings ("Use Hardware acceleration when available"):

![screenshot-20180712-095307](https://user-images.githubusercontent.com/877229/42619862-879fae10-85b9-11e8-9db8-1d5dbd4744b4.png)

**Comment by nickpeihl** [comment]
Looks like we can test for this in the mapbox-gl library. https://www.mapbox.com/mapbox-gl-js/example/check-for-support/
