### ISSUE TITLE
Migrate to Elastic License v2

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-landing-page#333]
The Elastic License has been superseded by the simpler and more permissive [Elastic License v2](https://www.elastic.co/licensing/elastic-license). I propose we change the license for this repository to the Elastic License v2 starting with v7.14.

I believe this license change should be a no-op since the ems-landing-page is not an NPM module or dependency of any external products.

@elastic/kibana-gis

**Comment by jsanz** [comment]
> I believe this license change should be a no-op since the ems-landing-page is not an NPM module or dependency of any external products.

But we should still update the [repo license](https://github.com/elastic/ems-landing-page/blob/master/ELASTIC-LICENSE.txt), right?
