### ISSUE TITLE
maps.elastic.co is showing staging layers

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-landing-page#36]
If you check the network tab in the developer tools when loading https://maps.elastic.co you'll see that it is loading the EMS staging manifest instead of production. 

<img width="1282" alt="screen shot 2018-07-18 at 11 56 28 am" src="https://user-images.githubusercontent.com/1638483/42901899-acb90968-8a81-11e8-82cf-1afcfcfd33a1.png">

**Comment by nyurik** [comment]
Can the code check if the current host is `http://maps-staging.elastic.co` (or possibly localhost ?) and use staging manifest?

**Comment by nickpeihl** [comment]
This is not a problem anymore. #37 did fix this so I may have been fooled by a cache.
