### ISSUE TITLE
[Discuss] Remove CI build jobs for older releases

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-landing-page#369]
With Elastic Stack 8.0 coming out soon, I'd like to consider cleaning up some of the [older CI build jobs](https://github.com/elastic/ems-landing-page/tree/master/.ci/jobs) for EMS Landing Page. I think we could remove all jobs prior to 7.15 since there are no further matching stack releases.

Under this proposal [older branches](https://github.com/elastic/ems-landing-page/branches) and webpages (such as https://maps.elastic.co/v7.10) of ems-landing-page would be essentially frozen with no further updates. This is consistent with other products in the stack.

The jobs I'm proposing to remove are
- elastic+ems-landing-page+v2+stage.yml
- elastic+ems-landing-page+v6.6+stage.yml
- elastic+ems-landing-page+v6.7+stage.yml
- elastic+ems-landing-page+v7.0+stage.yml
- elastic+ems-landing-page+v7.2+stage.yml
- elastic+ems-landing-page+v7.4+stage.yml
- elastic+ems-landing-page+v7.6.yml
- elastic+ems-landing-page+v7.7.yml
- elastic+ems-landing-page+v7.8.yml
- elastic+ems-landing-page+v7.9.yml
- elastic+ems-landing-page+v7.10.yml
- elastic+ems-landing-page+v7.11.yml
- elastic+ems-landing-page+v7.12.yml
- elastic+ems-landing-page+v7.13.yml
- elastic+ems-landing-page+v7.14.yml

There was a related effort to reduce builds in https://github.com/elastic/ems-landing-page/pull/229 with client-side routing, but that is proving too difficult.

Thoughts @jsanz @nyurik @thomasneirynck?

**Comment by jsanz** [comment]
@nyurik @nickpeihl can we move forward and remove those CI jobs and related backport configuration?

Is there anything else to do apart from creating a PR removing the Jenkins configuration files from the infra side or Jenkins will pick up the absent files and remove the entries in the UI?
