### ISSUE TITLE
App hangs when URL hash-params are malformed

### ISSUE THREAD

**Issue by thomasneirynck** [elastic/ems-landing-page#88]
When a tweet goes out, the framework adds query-params after the hash in the URL.

e.g: in https://twitter.com/elastic/status/1112831884772356096

`https://maps.elastic.co/#file/world_countries?blade=tw&hulk=social`

That is a malformed URL, the query-params (`blade=tw&hulk=social`) should go before the hash-params (`#file/world_countries`). So the "correct" URL should be `https://maps.elastic.co/?blade=tw&hulk=social#file/world_countries`

This causes the to display the spinner indefinitely.

**Comment by nickpeihl** [comment]
I submitted a fix that partially addresses this in #186. However, I'm not sure we can do much to resolve the malformed URL. I believe the onus is on the social team to ensure the URL is formed correctly.

**Comment by thomasneirynck** [comment]
+1 on just handling empty params on our end, but that the URL-formatting should be "correct" in the tweets. Likely due to url-shortening system or something.

cc @dsmith001 Is this something you know more about?

**Comment by dsmith001** [comment]
@thomasneirynck @nickpeihl Awesome detective work!  Let me raise a ticket with the social media team.
