### ISSUE TITLE
Zoom levels >10 not available

### ISSUE THREAD

**Issue by nickpeihl** [elastic/ems-landing-page#91]
The map on maps.elastic.co does not have a maximum zoom level defined, but requests for tiles greater than zoom level 10 will fail because there is no license.

If we want users to be able to zoom to levels >10 we need to supply a license to Elastic Maps Service. 

Alternatively, we could set a max zoom parameter on the map itself to stop at zoom level 10.

**Comment by nyurik** [comment]
I think we should supply a proper license, because that will allow quick internal testing, share links in case of issues, and also be good if people want to explore our maps in depth.
